name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t samsonyi/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true samsonyi/react-test npm test
 
      - run: docker build -t samsonyi/multi-client ./client
      - run: docker build -t samsonyi/multi-nginx ./nginx
      - run: docker build -t samsonyi/multi-server ./server
      - run: docker build -t samsonyi/multi-worker ./worker
 
      - run: docker push samsonyi/multi-client
      - run: docker push samsonyi/multi-nginx
      - run: docker push samsonyi/multi-server
      - run: docker push samsonyi/multi-worker