name: Deploy MultiDocker
on:
  push:
    branches:
      - master
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t samsonyi/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true samsonyi/react-test npm test
 
      - run: docker build -t samsonyi/multi-client-10-14 ./client
      - run: docker build -t samsonyi/multi-nginx-10-14 ./nginx
      - run: docker build -t samsonyi/multi-server-10-14 ./server
      - run: docker build -t samsonyi/multi-worker-10-14 ./worker
 
      - run: docker push samsonyi/multi-client-10-14
      - run: docker push samsonyi/multi-nginx-10-14
      - run: docker push samsonyi/multi-server-10-14
      - run: docker push samsonyi/multi-worker-10-14